import type { HandoverForm, HandoverState } from "./types"
import RecaptchaDisclosure from "@modules/common/components/recaptcha-disclosure"
import { SupportIcon } from "./chatbot-icons"

type Props = {
  handover: HandoverState
  form: HandoverForm
  expanded: boolean
  busy: boolean
  error: string
  onExpand: () => void
  onFormChange: (form: HandoverForm) => void
  onCreate: () => void
  onWhatsApp: () => void
}

export default function ChatbotHandover({ handover, form, expanded, busy, error, onExpand, onFormChange, onCreate, onWhatsApp }: Props) {
  if (handover.reference) return <section className="cba-chatbot-message rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-emerald-600 text-white"><SupportIcon className="h-5 w-5"/></span><div><h3 className="text-sm font-bold text-emerald-950">CBA support request ready</h3><p className="mt-1 text-xs leading-5 text-emerald-900">Reference <strong>{handover.reference}</strong></p></div></div>{handover.whatsapp_url ? <a href={handover.whatsapp_url} target="_blank" rel="noopener noreferrer" onClick={onWhatsApp} className="mt-3 flex min-h-11 w-full items-center justify-center rounded-xl bg-[#25D366] px-4 text-sm font-bold text-white transition hover:bg-[#1fbd5a] focus:outline-none focus-visible:ring-4 focus-visible:ring-emerald-300">Continue on WhatsApp</a> : <p role="alert" className="mt-3 rounded-lg bg-amber-100 px-3 py-2 text-xs font-medium text-amber-900">WhatsApp is currently unavailable. Please use the Contact page.</p>}</section>

  return <section className="cba-chatbot-message overflow-hidden rounded-2xl border border-orange-200 bg-[#fff8f3]"><div className="p-4"><div className="flex gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand/10 text-brand"><SupportIcon className="h-5 w-5"/></span><div className="min-w-0"><h3 className="text-sm font-bold text-grey-90">Need help from a person?</h3><p className="mt-1 text-xs leading-5 text-grey-60">Share your contact details and the CBA support team can continue with you on WhatsApp.</p></div></div>{!expanded ? <button type="button" onClick={onExpand} className="mt-3 flex min-h-11 w-full items-center justify-center rounded-xl bg-[#221f1f] px-4 text-sm font-bold text-white transition hover:bg-black focus:outline-none focus-visible:ring-4 focus-visible:ring-grey-30">Talk to CBA support</button> : <div className="mt-4 space-y-3 border-t border-orange-200 pt-4"><label className="block text-xs font-semibold text-grey-70">Name<input autoComplete="name" value={form.name} onChange={(event) => onFormChange({ ...form, name: event.target.value })} placeholder="Your name" className="mt-1.5 h-11 w-full rounded-xl border border-grey-30 bg-white px-3 text-sm outline-none transition focus:border-brand focus:ring-4 focus:ring-brand/10"/></label><label className="block text-xs font-semibold text-grey-70">WhatsApp number<input inputMode="tel" autoComplete="tel" value={form.phone} onChange={(event) => onFormChange({ ...form, phone: event.target.value })} placeholder="+94 77 123 4567" className="mt-1.5 h-11 w-full rounded-xl border border-grey-30 bg-white px-3 text-sm outline-none transition focus:border-brand focus:ring-4 focus:ring-brand/10"/></label><label className="flex cursor-pointer items-start gap-2.5 text-xs leading-5 text-grey-60"><input type="checkbox" checked={form.consent} onChange={(event) => onFormChange({ ...form, consent: event.target.checked })} className="mt-1 h-4 w-4 rounded border-grey-30 accent-[#ff5c0e]"/><span>I consent to CBA receiving my contact details and a short chat summary.</span></label>{error ? <p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-xs font-medium text-red-700">{error}</p> : null}<button type="button" onClick={onCreate} disabled={busy} className="flex min-h-11 w-full items-center justify-center rounded-xl bg-[#221f1f] px-4 text-sm font-bold text-white transition hover:bg-black focus:outline-none focus-visible:ring-4 focus-visible:ring-grey-30 disabled:cursor-wait disabled:opacity-50">{busy ? "Creating request…" : "Create support request"}</button><RecaptchaDisclosure /></div>}</div></section>
}
