FROM node:22.13.0-alpine AS deps

WORKDIR /app
ENV CI=true

COPY package.json package-lock.json ./
RUN npm install --include=dev --no-audit --no-fund

FROM node:22.13.0-alpine AS builder

WORKDIR /app
ENV CI=true
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG MEDUSA_BACKEND_URL
ARG NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_DEFAULT_REGION
ARG NEXT_PUBLIC_STRIPE_KEY
ARG NEXT_PUBLIC_MEDUSA_PAYMENTS_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_MEDUSA_PAYMENTS_ACCOUNT_ID
ARG MEDUSA_CLOUD_S3_HOSTNAME
ARG MEDUSA_CLOUD_S3_PATHNAME
ARG AUTH_COOKIE_NAME
ARG CART_COOKIE_NAME
ARG CACHE_COOKIE_NAME

ENV MEDUSA_BACKEND_URL=${MEDUSA_BACKEND_URL}
ENV NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY}
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
ENV NEXT_PUBLIC_DEFAULT_REGION=${NEXT_PUBLIC_DEFAULT_REGION}
ENV NEXT_PUBLIC_STRIPE_KEY=${NEXT_PUBLIC_STRIPE_KEY}
ENV NEXT_PUBLIC_MEDUSA_PAYMENTS_PUBLISHABLE_KEY=${NEXT_PUBLIC_MEDUSA_PAYMENTS_PUBLISHABLE_KEY}
ENV NEXT_PUBLIC_MEDUSA_PAYMENTS_ACCOUNT_ID=${NEXT_PUBLIC_MEDUSA_PAYMENTS_ACCOUNT_ID}
ENV MEDUSA_CLOUD_S3_HOSTNAME=${MEDUSA_CLOUD_S3_HOSTNAME}
ENV MEDUSA_CLOUD_S3_PATHNAME=${MEDUSA_CLOUD_S3_PATHNAME}

RUN npm run build

FROM node:22.13.0-alpine AS runner

WORKDIR /app

ARG MEDUSA_BACKEND_URL
ARG NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_DEFAULT_REGION
ARG NEXT_PUBLIC_STRIPE_KEY
ARG NEXT_PUBLIC_MEDUSA_PAYMENTS_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_MEDUSA_PAYMENTS_ACCOUNT_ID
ARG MEDUSA_CLOUD_S3_HOSTNAME
ARG MEDUSA_CLOUD_S3_PATHNAME
ARG AUTH_COOKIE_NAME
ARG CART_COOKIE_NAME
ARG CACHE_COOKIE_NAME

ENV NODE_ENV=production
ENV PORT=8000
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1
ENV MEDUSA_BACKEND_URL=${MEDUSA_BACKEND_URL}
ENV NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY}
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
ENV NEXT_PUBLIC_DEFAULT_REGION=${NEXT_PUBLIC_DEFAULT_REGION}
ENV NEXT_PUBLIC_STRIPE_KEY=${NEXT_PUBLIC_STRIPE_KEY}
ENV NEXT_PUBLIC_MEDUSA_PAYMENTS_PUBLISHABLE_KEY=${NEXT_PUBLIC_MEDUSA_PAYMENTS_PUBLISHABLE_KEY}
ENV NEXT_PUBLIC_MEDUSA_PAYMENTS_ACCOUNT_ID=${NEXT_PUBLIC_MEDUSA_PAYMENTS_ACCOUNT_ID}
ENV MEDUSA_CLOUD_S3_HOSTNAME=${MEDUSA_CLOUD_S3_HOSTNAME}
ENV MEDUSA_CLOUD_S3_PATHNAME=${MEDUSA_CLOUD_S3_PATHNAME}
ENV AUTH_COOKIE_NAME=${AUTH_COOKIE_NAME}
ENV CART_COOKIE_NAME=${CART_COOKIE_NAME}
ENV CACHE_COOKIE_NAME=${CACHE_COOKIE_NAME}
ENV AUTH_COOKIE_NAME=${AUTH_COOKIE_NAME}
ENV CART_COOKIE_NAME=${CART_COOKIE_NAME}
ENV CACHE_COOKIE_NAME=${CACHE_COOKIE_NAME}

COPY --from=builder --chown=node:node /app/public ./public
COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static

EXPOSE 8000

USER node

CMD ["node", "server.js"]
